language: julia
os:
#  - osx
  - linux
julia:
  - 0.6
#  - 0.7
#  - nightly
notifications:
  email: false
addons:
    apt_packages:
        - gfortran
after_success:
  - julia -e 'cd(Pkg.dir("SVDD")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
